
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('@prisma/client/runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.MtBrandScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
};

exports.Prisma.MtCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  display_order: 'display_order',
  created_at: 'created_at'
};

exports.Prisma.MtColorScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.MtGenderScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name'
};

exports.Prisma.ProductImageScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  image_url: 'image_url',
  is_primary: 'is_primary',
  created_at: 'created_at'
};

exports.Prisma.ProductVariantScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  color_id: 'color_id',
  size_id: 'size_id',
  sku: 'sku',
  stock: 'stock',
  price: 'price',
  discount_price: 'discount_price',
  discount_percent: 'discount_percent',
  discount_start: 'discount_start',
  discount_end: 'discount_end'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  category_id: 'category_id',
  brand_id: 'brand_id',
  base_price: 'base_price',
  is_active: 'is_active',
  created_at: 'created_at',
  gender_id: 'gender_id'
};

exports.Prisma.MtRoleScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.MtSizeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
};

exports.Prisma.MtStatusScalarFieldEnum = {
  id: 'id',
  type_status: 'type_status',
  code: 'code',
  name: 'name',
  description: 'description',
  is_active: 'is_active'
};

exports.Prisma.CartItemScalarFieldEnum = {
  id: 'id',
  cart_id: 'cart_id',
  product_variant_id: 'product_variant_id',
  qty: 'qty'
};

exports.Prisma.CartScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  created_at: 'created_at'
};

exports.Prisma.OrderItemScalarFieldEnum = {
  id: 'id',
  order_id: 'order_id',
  product_variant_id: 'product_variant_id',
  qty: 'qty',
  price: 'price',
  subtotal: 'subtotal'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  order_date: 'order_date',
  idempotency_key: 'idempotency_key',
  total_amount: 'total_amount',
  status: 'status',
  payment_status: 'payment_status',
  name: 'name',
  phone: 'phone',
  address: 'address',
  province_id: 'province_id',
  province_name: 'province_name',
  city_id: 'city_id',
  city_name: 'city_name',
  district_id: 'district_id',
  district_name: 'district_name',
  postal_code: 'postal_code',
  order_status_id: 'order_status_id',
  payment_status_id: 'payment_status_id',
  shipping_cost: 'shipping_cost',
  courier: 'courier',
  courier_service: 'courier_service'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  order_id: 'order_id',
  payment_method: 'payment_method',
  payment_date: 'payment_date',
  amount: 'amount',
  status: 'status',
  transaction_id: 'transaction_id',
  payment_method_id: 'payment_method_id',
  receipt_url: 'receipt_url',
  payment_url: 'payment_url',
  va_number: 'va_number',
  bank_code: 'bank_code',
  bank_name: 'bank_name',
  qr_string: 'qr_string',
  payment_id: 'payment_id',
  expired_at: 'expired_at'
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  product_id: 'product_id',
  rating: 'rating',
  comment: 'comment',
  created_at: 'created_at'
};

exports.Prisma.ShipmentScalarFieldEnum = {
  id: 'id',
  order_id: 'order_id',
  courier: 'courier',
  tracking_number: 'tracking_number',
  shipping_date: 'shipping_date',
  delivery_date: 'delivery_date',
  status: 'status',
  shipment_status_id: 'shipment_status_id'
};

exports.Prisma.UserAddressScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  label: 'label',
  recipient_name: 'recipient_name',
  phone: 'phone',
  address: 'address',
  province_id: 'province_id',
  province_name: 'province_name',
  city_id: 'city_id',
  city_name: 'city_name',
  district_id: 'district_id',
  district_name: 'district_name',
  postal_code: 'postal_code',
  is_default: 'is_default',
  created_at: 'created_at'
};

exports.Prisma.AdminAddressScalarFieldEnum = {
  id: 'id',
  label: 'label',
  recipient_name: 'recipient_name',
  phone: 'phone',
  address: 'address',
  province_id: 'province_id',
  province_name: 'province_name',
  city_id: 'city_id',
  city_name: 'city_name',
  district_id: 'district_id',
  district_name: 'district_name',
  postal_code: 'postal_code',
  is_active: 'is_active',
  created_at: 'created_at'
};

exports.Prisma.UserRoleScalarFieldEnum = {
  user_id: 'user_id',
  role_id: 'role_id'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  phone: 'phone',
  created_at: 'created_at'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  title: 'title',
  message: 'message',
  is_read: 'is_read',
  created_at: 'created_at'
};

exports.Prisma.WishlistScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  product_id: 'product_id',
  created_at: 'created_at'
};

exports.Prisma.AuditTrailScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  method: 'method',
  url: 'url',
  payload: 'payload',
  ip_address: 'ip_address',
  user_agent: 'user_agent',
  created_at: 'created_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.MtBrandOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description'
};

exports.Prisma.MtCategoryOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.MtColorOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.MtGenderOrderByRelevanceFieldEnum = {
  code: 'code',
  name: 'name'
};

exports.Prisma.ProductImageOrderByRelevanceFieldEnum = {
  image_url: 'image_url'
};

exports.Prisma.ProductVariantOrderByRelevanceFieldEnum = {
  sku: 'sku'
};

exports.Prisma.ProductOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description'
};

exports.Prisma.MtRoleOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.MtSizeOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description'
};

exports.Prisma.MtStatusOrderByRelevanceFieldEnum = {
  type_status: 'type_status',
  code: 'code',
  name: 'name',
  description: 'description'
};

exports.Prisma.CartOrderByRelevanceFieldEnum = {
  user_id: 'user_id'
};

exports.Prisma.OrderOrderByRelevanceFieldEnum = {
  user_id: 'user_id',
  idempotency_key: 'idempotency_key',
  status: 'status',
  payment_status: 'payment_status',
  name: 'name',
  phone: 'phone',
  address: 'address',
  province_id: 'province_id',
  province_name: 'province_name',
  city_id: 'city_id',
  city_name: 'city_name',
  district_id: 'district_id',
  district_name: 'district_name',
  postal_code: 'postal_code',
  courier: 'courier',
  courier_service: 'courier_service'
};

exports.Prisma.PaymentOrderByRelevanceFieldEnum = {
  payment_method: 'payment_method',
  status: 'status',
  transaction_id: 'transaction_id',
  receipt_url: 'receipt_url',
  payment_url: 'payment_url',
  va_number: 'va_number',
  bank_code: 'bank_code',
  bank_name: 'bank_name',
  qr_string: 'qr_string',
  payment_id: 'payment_id'
};

exports.Prisma.ReviewOrderByRelevanceFieldEnum = {
  user_id: 'user_id',
  comment: 'comment'
};

exports.Prisma.ShipmentOrderByRelevanceFieldEnum = {
  courier: 'courier',
  tracking_number: 'tracking_number',
  status: 'status'
};

exports.Prisma.UserAddressOrderByRelevanceFieldEnum = {
  user_id: 'user_id',
  label: 'label',
  recipient_name: 'recipient_name',
  phone: 'phone',
  address: 'address',
  province_id: 'province_id',
  province_name: 'province_name',
  city_id: 'city_id',
  city_name: 'city_name',
  district_id: 'district_id',
  district_name: 'district_name',
  postal_code: 'postal_code'
};

exports.Prisma.AdminAddressOrderByRelevanceFieldEnum = {
  label: 'label',
  recipient_name: 'recipient_name',
  phone: 'phone',
  address: 'address',
  province_id: 'province_id',
  province_name: 'province_name',
  city_id: 'city_id',
  city_name: 'city_name',
  district_id: 'district_id',
  district_name: 'district_name',
  postal_code: 'postal_code'
};

exports.Prisma.UserRoleOrderByRelevanceFieldEnum = {
  user_id: 'user_id'
};

exports.Prisma.UserOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  phone: 'phone'
};

exports.Prisma.NotificationOrderByRelevanceFieldEnum = {
  user_id: 'user_id',
  title: 'title',
  message: 'message'
};

exports.Prisma.WishlistOrderByRelevanceFieldEnum = {
  user_id: 'user_id'
};

exports.Prisma.AuditTrailOrderByRelevanceFieldEnum = {
  user_id: 'user_id',
  method: 'method',
  url: 'url',
  payload: 'payload',
  ip_address: 'ip_address',
  user_agent: 'user_agent'
};


exports.Prisma.ModelName = {
  MtBrand: 'MtBrand',
  MtCategory: 'MtCategory',
  MtColor: 'MtColor',
  MtGender: 'MtGender',
  ProductImage: 'ProductImage',
  ProductVariant: 'ProductVariant',
  Product: 'Product',
  MtRole: 'MtRole',
  MtSize: 'MtSize',
  MtStatus: 'MtStatus',
  CartItem: 'CartItem',
  Cart: 'Cart',
  OrderItem: 'OrderItem',
  Order: 'Order',
  Payment: 'Payment',
  Review: 'Review',
  Shipment: 'Shipment',
  UserAddress: 'UserAddress',
  AdminAddress: 'AdminAddress',
  UserRole: 'UserRole',
  User: 'User',
  Notification: 'Notification',
  Wishlist: 'Wishlist',
  AuditTrail: 'AuditTrail'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
